name: "Build & test workflow skeleton"

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
        
  build:
    name: "🚧 - Build & Test"
    runs-on: ubuntu-latest  

    steps:
      - run: echo "implement your own build and test logic here"
